import {
  FileText,
  Cpu,
  Monitor,
  Code,
  BarChart3,
  Bot,
  ShieldAlert,
  Boxes,
  Briefcase,
  Coins,
  Megaphone,
  ShoppingBag,
  Rocket,
  Palette,
  Film,
  Camera,
  HeartPulse,
  Scale,
  Milestone,
  Building2,
  Languages,
  Users2,
  Hotel,
  Plane,
  Compass,
  CalendarDays,
  Scissors,
  Smile,
  Music,
  Trophy,
} from "lucide-react";

// Same 30-category pool + card styling as src/pages/Categories.jsx —
// kept here so Home page widgets can reuse the identical design.
export const EXPLORE_CATEGORIES = [
  { label: "Government Exams", icon: FileText, bg: "from-emerald-500/10 to-teal-500/5", iconColor: "text-emerald-600" },
  { label: "Engineering", icon: Cpu, bg: "from-purple-500/10 to-indigo-500/5", iconColor: "text-purple-600" },
  { label: "Information Technology", icon: Monitor, bg: "from-blue-500/10 to-sky-500/5", iconColor: "text-blue-500" },
  { label: "Software Development", icon: Code, bg: "from-indigo-500/10 to-blue-500/5", iconColor: "text-indigo-600" },
  { label: "Data Science", icon: BarChart3, bg: "from-teal-500/10 to-cyan-500/5", iconColor: "text-teal-600" },
  { label: "Artificial Intelligence", icon: Bot, bg: "from-violet-500/10 to-purple-500/5", iconColor: "text-violet-600" },
  { label: "Cyber Security", icon: ShieldAlert, bg: "from-red-500/10 to-orange-500/5", iconColor: "text-red-600" },
  { label: "Cloud Computing", icon: Boxes, bg: "from-sky-500/10 to-cyan-500/5", iconColor: "text-sky-600" },
  { label: "Business Management", icon: Briefcase, bg: "from-orange-500/10 to-amber-500/5", iconColor: "text-orange-600" },
  { label: "Finance", icon: Coins, bg: "from-green-500/10 to-emerald-500/5", iconColor: "text-green-600" },
  { label: "Digital Marketing", icon: Megaphone, bg: "from-rose-500/10 to-orange-500/5", iconColor: "text-rose-600" },
  { label: "Sales", icon: ShoppingBag, bg: "from-orange-500/10 to-yellow-500/5", iconColor: "text-orange-500" },
  { label: "Entrepreneurship", icon: Rocket, bg: "from-blue-500/10 to-indigo-500/5", iconColor: "text-blue-600" },
  { label: "Design", icon: Palette, bg: "from-purple-500/10 to-pink-500/5", iconColor: "text-purple-600" },
  { label: "Animation", icon: Film, bg: "from-pink-500/10 to-rose-500/5", iconColor: "text-pink-600" },
  { label: "Video Editing", icon: Camera, bg: "from-red-500/10 to-pink-500/5", iconColor: "text-red-500" },
  { label: "Healthcare", icon: HeartPulse, bg: "from-emerald-500/10 to-teal-500/5", iconColor: "text-emerald-600" },
  { label: "Law", icon: Scale, bg: "from-amber-500/10 to-orange-500/5", iconColor: "text-amber-600" },
  { label: "Architecture", icon: Milestone, bg: "from-cyan-500/10 to-blue-500/5", iconColor: "text-cyan-600" },
  { label: "Interior Design", icon: Building2, bg: "from-orange-500/10 to-amber-500/5", iconColor: "text-orange-600" },
  { label: "Languages", icon: Languages, bg: "from-orange-500/10 to-rose-500/5", iconColor: "text-orange-500" },
  { label: "Personality Development", icon: Users2, bg: "from-green-500/10 to-emerald-500/5", iconColor: "text-green-600" },
  { label: "Hospitality", icon: Hotel, bg: "from-emerald-500/10 to-teal-500/5", iconColor: "text-emerald-600" },
  { label: "Aviation", icon: Plane, bg: "from-sky-500/10 to-cyan-500/5", iconColor: "text-sky-600" },
  { label: "Travel & Tourism", icon: Compass, bg: "from-blue-500/10 to-cyan-500/5", iconColor: "text-blue-500" },
  { label: "Event Management", icon: CalendarDays, bg: "from-orange-500/10 to-amber-500/5", iconColor: "text-orange-500" },
  { label: "Fashion Design", icon: Scissors, bg: "from-purple-500/10 to-violet-500/5", iconColor: "text-purple-500" },
  { label: "Beauty & Wellness", icon: Smile, bg: "from-rose-500/10 to-pink-500/5", iconColor: "text-rose-500" },
  { label: "Music & Performing Arts", icon: Music, bg: "from-pink-500/10 to-rose-500/5", iconColor: "text-pink-500" },
  { label: "Sports & Fitness", icon: Trophy, bg: "from-emerald-500/10 to-green-500/5", iconColor: "text-emerald-600" },
];
