// Shared dropdown option lists used by both the student profile page
// (dashboard/student/pages/Profile.jsx) and the student signup flow
// (components/onboarding/Onboardingsteps.jsx) so the two stay in sync.

export const genderOptions = ["Male", "Female", "Non-Binary", "Prefer Not to Say"];
export const maritalOptions = ["Single", "Married", "Separated", "Prefer Not to Say"];
export const qualificationOptions = [
  "12th",
  "Certificate",
  "ITI",
  "Diploma",
  "Under Graduation",
  "Graduation",
  "Post Graduation",
  "Master's Degree",
  "PHD",
  "Other",
];

export const employmentStatuses = [
  "Intern",
  "Employed Full-Time",
  "Employed Part-Time",
  "Freelancer",
  "Self-Employed",
  "Business Owner",
  "Teacher / Educator",
  "Unemployed",
  "Retired",
];

export const experienceOptions = [
  "Fresher (0 Years)",
  "Less than 1 Year",
  "1-2 Years",
  "3-5 Years",
  "6-10 Years",
  "11-15 Years",
  "15+ Years",
];

export const industryOptions = [
  "Information Technology",
  "Artificial Intelligence",
  "Software Development",
  "Finance",
  "Banking",
  "Accounting",
  "Healthcare",
  "Education",
  "Government",
  "Manufacturing",
  "Construction",
  "Real Estate",
  "Retail",
  "E-Commerce",
  "Logistics",
  "Hospitality",
  "Aviation",
  "Media & Entertainment",
  "Marketing & Advertising",
  "Telecommunications",
  "Agriculture",
  "Legal Services",
  "Other",
];

export const careerGoalOptions = [
  "Switch career",
  "Upskill",
  "Promotion",
  "Start business",
  "Explore options",
];

export const languageOptions = [
  "English",
  "Mandarin Chinese",
  "Hindi",
  "Spanish",
  "French",
  "Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Nigerian Pidgin",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Vietnamese",
  "Korean",
  "Persian (Farsi)",
  "Italian",
  "Gujarati",
  "Polish",
  "Ukrainian",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Thai",
  "Dutch",
  "Romanian",
  "Czech",
  "Greek",
  "Hungarian",
  "Swedish",
  "Danish",
  "Norwegian",
  "Finnish",
  "Slovak",
  "Bulgarian",
  "Serbian",
  "Croatian",
  "Slovenian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Albanian",
  "Macedonian",
  "Bosnian",
  "Hebrew",
  "Swahili",
  "Filipino (Tagalog)",
  "Malay",
  "Burmese (Myanmar)",
  "Khmer",
  "Lao",
  "Nepali",
  "Sinhala",
  "Pashto",
  "Dari",
  "Azerbaijani",
  "Kazakh",
  "Uzbek",
  "Turkmen",
  "Kyrgyz",
  "Tajik",
  "Mongolian",
  "Tibetan",
  "Georgian",
  "Armenian",
  "Amharic",
  "Somali",
  "Yoruba",
  "Igbo",
  "Hausa",
  "Zulu",
  "Xhosa",
  "Afrikaans",
  "Icelandic",
  "Irish",
  "Welsh",
  "Scottish Gaelic",
  "Catalan",
  "Basque",
  "Galician",
  "Luxembourgish",
  "Maltese",
  "Assamese",
  "Odia",
  "Konkani",
  "Kashmiri",
  "Sanskrit",
  "Sindhi",
  "Dogri",
  "Bodo",
  "Santali",
  "Tulu",
];

export const hobbyOptions = [
  "Reading",
  "Writing",
  "Drawing & Sketching",
  "Painting",
  "Photography",
  "Videography",
  "Music",
  "Singing",
  "Dancing",
  "Cooking",
  "Baking",
  "Travelling",
  "Gardening",
  "Public Speaking",
  "Volunteering",
  "Content Creation",
  "Blogging",
  "Podcasting",
  "Debate & Discussion",
  "Indoor Games",
  "Outdoor Games",
  "Digital Games",
  "DIY & Craft",
  "Technology",
  "Fitness",
  "Meditation",
  "Yoga",
  "Social Work",
  "Event Participation",
  "Theatre & Acting",
  "Storytelling",
  "Fashion & Styling",
  "Designing",
  "Collecting",
  "Learning Languages",
  "Nature Exploration",
  "Personal Finance",
  "Entrepreneurship",
  "Helping Others",
  "Researching Online",
  "Watching Educational Videos",
  "Other",
];

export const skillOptions = [
  "AI Tools & Automation",
  "Prompting & AI Research",
  "Chatbot Building",
  "No-Code App Building",
  "Website Building",
  "App Development",
  "Cybersecurity",
  "Ethical Hacking",
  "Data Analytics",
  "Data Visualization",
  "Digital Marketing",
  "Social Media Growth",
  "Content Creation",
  "Video Editing",
  "Graphic Design",
  "UI/UX Design",
  "Product Design",
  "Personal Branding",
  "Copywriting",
  "Sales & Persuasion",
  "Communication Confidence",
  "Public Speaking",
  "Language Fluency",
  "Public speaking",
  "Communication",
  "Leadership",
  "Negotiation",
  "Startup & Business Skills",
  "Freelancing",
  "E-commerce",
  "Money Management",
  "Investing Basics",
  "Business Finance",
  "Career Planning",
  "Resume & Interview Skills",
  "Problem Solving",
  "Critical Thinking",
  "Project Execution",
  "Community Building",
  "Event Management",
  "Teaching & Mentoring",
  "Research Skills",
  "Other",
];

export const sportOptions = [
  "Gym & Strength Training",
  "Running",
  "Walking",
  "Yoga",
  "Meditation",
  "Swimming",
  "Cycling",
  "Football",
  "Cricket",
  "Basketball",
  "Badminton",
  "Tennis",
  "Volleyball",
  "Table Tennis",
  "Athletics",
  "Boxing",
  "Martial Arts",
  "Kickboxing",
  "Dance Fitness",
  "Zumba",
  "Calisthenics",
  "Skating",
  "Trekking",
  "Hiking",
  "Outdoor Fitness",
  "Sports Coaching",
  "Sports Nutrition",
  "Fitness Training",
  "Weight Loss",
  "General Fitness",
  "Other",
];
